'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class IssuingDet
    Public Property numIssDetID As Decimal
    Public Property numIssID As Decimal
    Public Property varCaseNo As String
    Public Property varCartonNo As String
    Public Property varPLNo As String
    Public Property numSKUID As Decimal
    Public Property varLotNo As String
    Public Property dteMftdDate As Date
    Public Property dteExpireDate As Date
    Public Property varUOMCode As String
    Public Property chrProdStatCode As String
    Public Property numLocationID As Decimal
    Public Property numPODetID As Decimal
    Public Property numPreIssuDetID As Nullable(Of Decimal)
    Public Property varCrtnNo As String
    Public Property numOrderQTY As Nullable(Of Decimal)
    Public Property numConfirmQTY As Nullable(Of Decimal)
    Public Property varRemarks As String
    Public Property numNewCrtn As Nullable(Of Decimal)
    Public Property numPolybagsUsed As Nullable(Of Decimal)
    Public Property varCreateBy As String
    Public Property dteCreateOn As Nullable(Of Date)
    Public Property varUpdateBy As String
    Public Property dteUpdateOn As Nullable(Of Date)
    Public Property varSSCCNumber As String

End Class
